### ISSUE TITLE
Sampling not working after Bokeh Update 0.12.10

### ISSUE THREAD

**Issue by FrancescaTaddei** [ChairOfStructuralMechanicsTUM/Mechanics_Apps#22]
![unbenannt](https://user-images.githubusercontent.com/25368100/32366661-546b7cfe-c07f-11e7-9be0-f2fa91ac9c1d.JPG)

**Comment by qaumann** [comment]
It should work as of commit b85bcbc

**Comment by FrancescaTaddei** [comment]
Thanks. Solved
