### ISSUE TITLE
Mathjax Problem

### ISSUE THREAD

**Issue by FrancescaTaddei** [ChairOfStructuralMechanicsTUM/Mechanics_Apps#24]
@CarmenFont 
The mathjax does not translate the Latex Formulas properly

**Comment by qaumann** [comment]
To make the Latex code work with Mathjax, the following code has to be put into the `<head>` of `templates/index.html` of the respective app:
```html
<script type="text/javascript" async
        src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
```
If `index.html` does not exist, an example can be found in the SDOF app.
