### ISSUE TITLE
Couple Moment

### ISSUE THREAD

**Issue by FrancescaTaddei** [ChairOfStructuralMechanicsTUM/Mechanics_Apps#25]
@rishithellathmeethal:
Carmen @CarmenFont will test the app and check for improvemnts

**Comment by CarmenFont** [comment]
Hi @rishithellathmeethal, 
your app works very well. However the cmd desplays a bokeh warning (see image below). Could you take a look at it and see if you can solve it? 

![image](https://user-images.githubusercontent.com/33516194/35158040-2c14282a-fd36-11e7-9955-d45cc46da886.png)
