### ISSUE TITLE
Eliminate global variables in Damped_oszillator and SDOF

### ISSUE THREAD

**Issue by axelgreim** [ChairOfStructuralMechanicsTUM/Mechanics_Apps#32]
The two apps Damped_oszillator and SDOF do not run, when launched on the same server. Probably, because parts of Damped_oszillator have been copied, when SDOF has been developed and global variables are used. Please eliminate all global variables...

**Comment by CarmenFont** [comment]
Eliminating global variables created new problems (buttons did not work anymore, ...)
Bug solved by changing the names of the files spring, mass and dashpot to spring1, mass1, dashpot1.
