### ISSUE TITLE
Collission app a bit unintuitive

### ISSUE THREAD

**Issue by BenjaminRueth** [ChairOfStructuralMechanicsTUM/Mechanics_Apps#4]
I think it is a bit unintuitive, that the collision animation starts right away. Would it be better to let the user manually start the animation by pressing **Play**?

**Comment by moustafabachar** [comment]
of course, I will work on it tomorrow.

**Comment by axelgreim** [comment]
I've finalized the collision app. francesca will put it online now. I've removed bugs occuring with the reset button. I've merged the Play and Pause bottons to one Play/Pause Button. I have used colors from the Styleguide of TUM....

Thank you all for your contribution!

**Comment by axelgreim** [comment]
App finished - issue closed...
