### ISSUE TITLE
Bug: Rollversuch

### ISSUE THREAD

**Issue by BenjaminRueth** [ChairOfStructuralMechanicsTUM/Mechanics_Apps#5]
On my computer the sphere, cylinder and tube do not look round. I can fix this by changing the figure height, but can we somehow force bokeh to always create figures with equal x and y unit?

![image](https://cloud.githubusercontent.com/assets/5740604/25585113/565d942a-2e99-11e7-9f10-eeb22a1ad378.png)

**Comment by EmilyBourne** [comment]
This should be fixed. Feel free to close the issue if it also looks right now on your computer

**Comment by BenjaminRueth** [comment]
Now everything is nice and round :)
