### ISSUE TITLE
Zero division error in SDOF app

### ISSUE THREAD

**Issue by qaumann** [ChairOfStructuralMechanicsTUM/Mechanics_Apps#50]
There appears to be an uncaught division by zero exception in the SDOF app. Could someone please take a look?
![grafik](https://user-images.githubusercontent.com/27352976/42587246-62d7d910-853a-11e8-8c18-fe336fe95356.png)

**Comment by m3bert** [comment]
For the case force>0 and D==1 the variable damped_ef is 0, but there was no case distinction like in the else-branch. 
I added an D==1 case and committed it to the git branch "SDOF-divzero-error" https://github.com/ChairOfStructuralMechanicsTUM/Mechanics_Apps/blob/SDOF-divzero-error/SDOF/main.py
Is this still mathematically correct and/or do we need cases for negative and positive D like in the force==1 (else) branch below?

**Comment by qaumann** [comment]
There is as far as I know no closed solution for harmonic excitation for critically oder overdamped systems. Could you include a function to deactivate the play button if there is a force present and the damping ratio D is equal or greater than 1?
Thanks a lot.

**Comment by m3bert** [comment]
Done.

I noticed that for some paramaters the change functions do not respond, when the play button is active.
(force, frequency ratio, initial displacement, initial velocity)
I understand this for the initial configurations but is this also needed for the force and frequency?
For the force slider I changed it for test reasons, however it can be easily changed again by removing the comment.

**Comment by qaumann** [comment]
Yes, this is intended. No slider should be active as long as the animation is running. Apparently, the `active=false` property did not exist, wehn the app was developed. Could you please take care of the following things:

- [ ] There should be a Play/Pause button saying Play when the animation is on hold and Pause when it is running (see e.g. https://gist.github.com/yingminc/1fcb2c6ef51a1c3f211c9d76aac25e1d).
- [ ] The silders should only be active, if nothing is displayed in the plot area. So as soon as the play button is pressed, all sliders should be deactivated. When the user presses the stop button, the plot area is cleared and the sliders are active again.
- [ ] Remove the Bokeh-logos
- [ ] It would be cool, if the force arrow would acutally show the force and its direction which is applied right now. It is a sinusoidal force depending on capital Omega (F*sin(Omega*t)). Could you take a look at this?

**Comment by m3bert** [comment]
I will have a look at the force arrow on Wednesday, after my exams.
It also seems that something regarding the callback functions should be changed:
"BokehDeprecationWarning: The ability to remove a callback function using its value was deprecated in Bokeh 0.12.15 and will be removed, use a value returned from the function that adds a callback instead."

**Comment by qaumann** [comment]
Thank you for your efforts. To avoid this warning, it is apparently the now proper way to do something like this:

```python
def animate():
        global callback_id
        if button.label == '► Play':
            button.label = '❚❚ Pause'
            callback_id = doc.add_periodic_callback(animate_update, 50)
        else:
            button.label = '► Play'
            doc.remove_periodic_callback(callback_id)
```

This comes at the cost of introducing even more global variables, but I cannot think of another way to change this without rearranging the whole structure of our apps...

**Comment by m3bert** [comment]
Maybe one could avoid the global variables by using ColumnDataSource objects. 
I will have a look at this next week. 
The rest should work now.

**Comment by qaumann** [comment]
That's a great idea, hopefully this can be implemented without too much effort.
The arrow visualization also looks impressive:) The only thing is when the arrow head changes from facing downwards to upwards, it looks like the arrow jumps. Could you perhaps include an offset, so the arrow head is "mirrored" at its baseline, when the orientation changes?
