### ISSUE TITLE
Pendulum: Bug in Trajectory

### ISSUE THREAD

**Issue by BenjaminRueth** [ChairOfStructuralMechanicsTUM/Mechanics_Apps#6]
In the Pendulum App there is something wrong with the trajectory:

![grafik](https://cloud.githubusercontent.com/assets/5740604/25947311/3b1f7cec-364f-11e7-8b05-4de107ba4ee8.png)

It seems like it has something to do with the startup of the app...

**Comment by EmilyBourne** [comment]
I spent ages trying to find what causes this, but as far as I can make out it's just that bokeh doesn't manage to save all the points at the beginning. The path was drawn with dots which made the problem a lot less obvious, but Francesca wanted a line to make it clearer in what order the points are visited. I'm not sure we can have it both ways though. I would suggest going back to dots and just making them smaller

**Comment by BenjaminRueth** [comment]
@ Francesca ?

**Comment by FrancescaTaddei** [comment]
With the dots would be fine. May  be just smaller than before. Shall I assign this task to someone or can you make this last change Emily @EmilyBourne ?

**Comment by EmilyBourne** [comment]
It's only 1 line, I've fixed it

**Comment by FrancescaTaddei** [comment]
Thanks @EmilyBourne
