### ISSUE TITLE
Federpendel: Critical Damping

### ISSUE THREAD

**Issue by BenjaminRueth** [ChairOfStructuralMechanicsTUM/Mechanics_Apps#7]
I think it would be nice and very instructive to have a one-click feature for setting a parameter set that causes critical damping. The parameter set m=2.5kg, k=10N/m and d=10Ns/m for example shows the effect. 

Another different approach: One could also provide the formulas in the app and let the student experiment with the parameters until critical damping occours. Some kind of feedback to signal "success" would be needed here.

Any opinions?

**Comment by FrancescaTaddei** [comment]
We can add a critical damping set. That sound better than a trial approach for the user. Also, we need to change the name, because spring pendulum is not appropriate. This is more an oscillator subjected to self weight.

**Comment by axelgreim** [comment]
I've augmented the daming slider in order to enable values up to 60Ns/m. In the descriptin is written now, that a value of 40Ns/m equals c_crit if the other parameters stay default.
Two bugs in damped oszillator remain. See Issues #31 and #32.
