### ISSUE TITLE
Rollercoaster, Collision, Projectiles: Server breakdown

### ISSUE THREAD

**Issue by BenjaminRueth** [ChairOfStructuralMechanicsTUM/Mechanics_Apps#8]
We observe a server breakdown in the following case:

* Start the server using Mechanic_Apps.exe
* Open Rollercoaster app from the overview page
* Close the Rollercoaster tab
* Open the Rollercoaster app again -> Error on the bokeh server

![grafik](https://cloud.githubusercontent.com/assets/5740604/26201067/6f36e876-3bd1-11e7-896a-d09d9bac985d.png)

# Progress

Is fixed

- [x] Rollercoaster
- [x] Projectiles
- [ ] Collision

**Comment by BenjaminRueth** [comment]
Is there maybe some not properly cleaned up javascript?

**Comment by BenjaminRueth** [comment]
We do not get this error if we open 2D cantilever beam or Balken in the same manner

**Comment by BenjaminRueth** [comment]
The same breakdown is observed in the Collision app.

**Comment by BenjaminRueth** [comment]
I tried to eliminate all globals to prevent breakdowns, but this did not help.

**Comment by BenjaminRueth** [comment]
Collision app still needs to be fixed! Rollercoaster works now.

**Comment by moustafabachar** [comment]
Hello Benjamin;

Can you give me any hint of what might be wrong with the Collision App?
Since you said that the Rollercoaster app was not working either, I assumed
it would be something wrong with the "mouse" interactivity.

I look forwards to hearing from you soon.

Regards,
Moustafa

**Comment by BenjaminRueth** [comment]
Hi Moustafa,

I got the Rollercoaster App working yesterday. Don't ask my why it works 
now...

Basically I did the a major refactoring, you can have a look at the 
changes using git diff or on the github website.

If you want to try to get the collision app working on your own, you 
could start by removing global variables as far as possible. Use classes 
for more complex objects (in the rollercoaster app this is for example 
the cart and the path) and add all the necessary logic to the respective 
class.

After doing this yesterday, the Rollercoaster app worked perfectly fine.

Best,
Benjamin

**Comment by FrancescaTaddei** [comment]
Let's see if we can fix it also on collision and lately I noticed it also happens on projectiles.

**Comment by FrancescaTaddei** [comment]
Let's see if we can fix it also on collision and lately I noticed it also happens on projectiles.

**Comment by FrancescaTaddei** [comment]
Let's see if we can fix it also on collision and lately I noticed it also happens on projectiles.

**Comment by BenjaminRueth** [comment]
At first glance the situation in Projectiles looks similar to the other two apps: Many global variables and from ... import *. We should try to avoid this in the future and maybe also add a remark to our programming guideline.

**Comment by BenjaminRueth** [comment]
Projectiles is fixed not. Some minor errors in the presentation of graphical content have been introduced (see #10 )

**Comment by BenjaminRueth** [comment]
How is it going with the collision app? Is it fixed?

**Comment by moustafabachar** [comment]
Hello Benjamin;

Not yet, but I will work on it when I finish the app I am working on right
now.

The modifications I am going to do is that I am going to remove the global
variables and try to use objects. I think that what I remember you said
previously, right?

**Comment by BenjaminRueth** [comment]
I just compared https://github.com/ChairOfStructuralMechanicsTUM/Mechanics_Apps/commit/24b2ad295fafd0417e79c34ffd2e4cc60ab98f60 (before fix) and https://github.com/ChairOfStructuralMechanicsTUM/Mechanics_Apps/commit/6809dadc279e7e8e4b83cd3a8a34b900d579d6bf (after fix). With the fixed version the bug in collision is resolved. Reloading the page does not crash the server anymore.
